name: owasp-zap-scan

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: OWASP ZAP API Scan
        uses: zaproxy/action-api-scan@v0.6.0
        continue-on-error: true
        with:
          target: https://ai-server-utim.onrender.com
          cmd_options: -J zap-result.json -r zap-report.html

      - uses: actions/upload-artifact@v4
        with:
          name: ZAP-HTML
          path: zap-report.html
